#!/usr/bin/env python3
"""
unpack.py — one-file cave bundle  ->  public/cave-pov/ (what the app serves).

The Darklake Cave first-person module is developed as ONE self-contained HTML file
(every image, sound and film inlined as a data: URI) so it can be previewed as a
claude.ai Artifact. The app should not ship a 12 MB HTML file, so this splits it:

    public/cave-pov/index.html   the page shell (styles, overlays, key legend)
    public/cave-pov/manifest.js  `const A = {...}` — the map, creatures, and asset URLs
    public/cave-pov/pov.js       the game (raycaster, controls, rules, sound)
    public/cave-pov/assets/*     every image / sound / film as a real file

Usage:  python3 scripts/cave/unpack.py darklake-cave.html [public/cave-pov]
The inverse is scripts/cave/bundle.py. pov.js loads audio from either form.
"""
import base64, json, os, re, sys, hashlib

src = sys.argv[1]
out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "..", "public", "cave-pov")
html = open(src, encoding="utf-8").read()
m = re.search(r"\n<script>\nconst A=", html)
assert m, "not a cave bundle: no inline `const A=` script"
top = html[: m.start()]
rest = html[m.end():]
end = rest.rindex("\n</script>")
body = rest[:end]
# the manifest is the first statement: a JSON object followed by ';\n'
dec = json.JSONDecoder()
A, n = dec.raw_decode(body)
js = body[n:].lstrip(";\n")

EXT = {"image/png": "png", "image/jpeg": "jpg", "image/webp": "webp", "audio/webm": "webm",
       "audio/mpeg": "mp3", "video/mp4": "mp4", "video/webm": "webm"}
os.makedirs(os.path.join(out, "assets"), exist_ok=True)
written = {}

def walk(node, path):
    if isinstance(node, dict):
        return {k: walk(v, path + [str(k)]) for k, v in node.items()}
    if isinstance(node, list):
        return [walk(v, path + [str(i)]) for i, v in enumerate(node)]
    if isinstance(node, str) and node.startswith("data:"):
        head, b64 = node.split(",", 1)
        mime = head[5:].split(";")[0]
        data = base64.b64decode(b64)
        name = "-".join(p for p in path if p not in ("src",)).replace("_", "-")
        name = re.sub(r"[^A-Za-z0-9.-]+", "-", name).strip("-") or hashlib.sha1(data).hexdigest()[:10]
        fn = f"{name}.{EXT.get(mime, 'bin')}"
        with open(os.path.join(out, "assets", fn), "wb") as f:
            f.write(data)
        written[fn] = len(data)
        return "assets/" + fn
    return node

A2 = walk(A, [])
with open(os.path.join(out, "manifest.js"), "w", encoding="utf-8") as f:
    f.write("// Generated by scripts/cave/unpack.py — the cave's map, creatures and asset URLs.\n")
    f.write("const A=" + json.dumps(A2, separators=(",", ":")) + ";\n")
with open(os.path.join(out, "pov.js"), "w", encoding="utf-8") as f:
    f.write(js.rstrip() + "\n")
shell = top.rstrip() + '\n<script src="manifest.js"></script>\n<script src="pov.js"></script>\n'
with open(os.path.join(out, "index.html"), "w", encoding="utf-8") as f:
    f.write(shell)
print(f"{len(written)} assets, {sum(written.values())//1024} KB -> {out}")
