#!/usr/bin/env python3
"""
Generate lib/spell-save-data.ts — which of the 556 spells call for a SAVE.

    python scripts/spells/build-save-map.py

WHY THIS EXISTS
---------------
lib/spellbook.ts knows about sixty-odd spells and carries `resolve: "save"` for
them. That was enough while only damaging spells needed drawing, and it broke
the moment enchantment arrived: 45 of the 57 enchantment spells call for a save
and most deal no damage at all, and the spellbook has never heard of Hold
Person, Charm Person or Command.

lib/data/spells.json has had the answer for all 556 the whole time, in the
`save` object. This lifts it into the same generated-map shape as
spell-school-data.ts so a target sigil can ask "does this spell call for a
save?" about any spell in the game rather than about the sixty that happen to
be hand-written.

It records the ABILITY, not just a boolean — an Intelligence save and a
Strength save are different beats, and a future sigil may well want to say so.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "lib" / "data" / "spells.json"
OUT = ROOT / "lib" / "spell-save-data.ts"

ABBREV = {
    "strength": "STR", "dexterity": "DEX", "constitution": "CON",
    "intelligence": "INT", "wisdom": "WIS", "charisma": "CHA",
}

def main() -> None:
    spells = json.loads(SRC.read_text())
    rows: dict[str, str] = {}
    for s in spells:
        save = s.get("save")
        if not save:
            continue
        code = ABBREV.get(str(save.get("ability", "")).strip().lower())
        if code:
            rows[s["name"].strip().lower()] = code

    lines = [
        "// GENERATED by scripts/spells/build-save-map.py — do not edit by hand.",
        "//",
        "// Spell name (lowercased) to the ability its SAVE is rolled against.",
        "// Absent means the spell calls for no save at all.",
        "//",
        "// Derived from lib/data/spells.json, which covers all 556 spells — unlike",
        "// lib/spellbook.ts, which hand-writes about sixty. Re-run the script",
        "// whenever that dataset changes.",
        f"// {len(rows)} spells call for a save.",
        "",
        "export type SaveAbility = \"STR\" | \"DEX\" | \"CON\" | \"INT\" | \"WIS\" | \"CHA\"",
        "",
        "export const SPELL_SAVE_ABILITY: Record<string, SaveAbility> = {",
    ]
    for name in sorted(rows):
        lines.append(f'  {json.dumps(name)}: "{rows[name]}",')
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{OUT.relative_to(ROOT)}: {len(rows)} of {len(spells)} spells call for a save")

if __name__ == "__main__":
    main()
