#!/usr/bin/env python3
"""
Derive lib/spell-school-data.ts from lib/data/spells.json.

The board needs a spell's 5E school to pick its rune, and lib/data/spells.json
is 377 KB — far too much to ship to a browser for one field per spell. This
emits a compact generated map instead: the spell name lowercased, against a
one-letter school code.

Generated, never hand-edited: the school of a spell is book data, and a
hand-kept copy is a second source of truth waiting to drift.

    python scripts/spells/build-school-map.py
"""
from __future__ import annotations
import json
from pathlib import Path

CODE = {
    "abjuration": "A", "conjuration": "C", "divination": "D", "enchantment": "E",
    "evocation": "V", "illusion": "I", "necromancy": "N", "transmutation": "T",
}

src = Path("lib/data/spells.json")
out = Path("lib/spell-school-data.ts")

spells = json.loads(src.read_text())
pairs: dict[str, str] = {}
missing: list[str] = []
for s in spells:
    name = (s.get("name") or "").strip().lower()
    school = (s.get("school") or "").strip().lower()
    if not name:
        continue
    code = CODE.get(school)
    if not code:
        missing.append(f"{name} ({school or 'no school'})")
        continue
    pairs[name] = code

body = "".join(f"  {json.dumps(k)}: {json.dumps(v)},\n" for k, v in sorted(pairs.items()))
out.write_text(
    "// GENERATED by scripts/spells/build-school-map.py — do not edit by hand.\n"
    "//\n"
    "// Spell name (lowercased) to its 5E school, one letter each:\n"
    "//   A abjuration  C conjuration  D divination  E enchantment\n"
    "//   V evocation   I illusion     N necromancy  T transmutation\n"
    "//\n"
    "// Derived from lib/data/spells.json so the school is never re-typed. Re-run\n"
    "// the script whenever that dataset changes.\n"
    f"// {len(pairs)} spells.\n\n"
    "export const SPELL_SCHOOL_CODES: Record<string, string> = {\n"
    f"{body}"
    "}\n"
)
print(f"wrote {out} — {len(pairs)} spells, {out.stat().st_size:,} bytes")
if missing:
    print(f"  {len(missing)} without a usable school: {', '.join(missing[:6])}")
