"use client"

import { useEffect, type ReactNode } from "react"
import { iconFor } from "@/lib/action-icons"
import { frameForClass } from "@/lib/class-frames"
import type { HudCharacter, HudLogLine } from "./combat-hud"
import { Globe } from "./essence-globe"
import { ClassMedallion } from "./class-medallion"

const ABIL = { str: "STR", dex: "DEX", con: "CON", int: "INT", wis: "WIS", cha: "CHA" } as const
type AbilKey = keyof typeof ABIL
const SKILLS: [string, AbilKey][] = [
  ["Acrobatics", "dex"], ["Animal Handling", "wis"], ["Arcana", "int"],
  ["Athletics", "str"], ["Deception", "cha"], ["History", "int"],
  ["Insight", "wis"], ["Intimidation", "cha"], ["Investigation", "int"],
  ["Medicine", "wis"], ["Nature", "int"], ["Perception", "wis"],
  ["Performance", "cha"], ["Persuasion", "cha"], ["Religion", "int"],
  ["Sleight of Hand", "dex"], ["Stealth", "dex"], ["Survival", "wis"],
]
const sign = (n: number) => `${n >= 0 ? "+" : ""}${n}`

function GothicPanel({ title, children, className = "", accent = "#a34de5" }: { title?: string; children: ReactNode; className?: string; accent?: string }) {
  return (
    <section className={`relative overflow-hidden border border-[#5b4626] bg-[linear-gradient(180deg,rgba(15,12,14,.985),rgba(5,4,6,.985))] shadow-[0_10px_26px_#000d,inset_0_0_0_1px_#d9ae5920] ${className}`}>
      <div className="pointer-events-none absolute inset-[3px] border border-[#2b2116]" />
      <i className="pointer-events-none absolute left-[5px] top-[5px] h-[8px] w-[8px] rotate-45 border border-[#8a6832] bg-[#080608]" />
      <i className="pointer-events-none absolute right-[5px] top-[5px] h-[8px] w-[8px] rotate-45 border border-[#8a6832] bg-[#080608]" />
      {title && <div className="relative border-b border-[#4a371e] bg-[linear-gradient(180deg,#24170e,#0c0808)] px-3 py-[7px] text-center font-serif text-[11px] uppercase tracking-[0.23em] text-[#d8b86e]"><span className="absolute inset-x-[20%] bottom-0 h-px" style={{ background: `linear-gradient(90deg,transparent,${accent}99,transparent)` }} />{title}</div>}
      <div className="relative p-2.5">{children}</div>
    </section>
  )
}

function CoreStat({ label, value, icon, accent }: { label: string; value: string | number; icon?: string; accent: string }) {
  return <div className="relative min-w-0 flex-1 border-r border-[#4a371f] bg-[linear-gradient(180deg,#0d0b10,#050406)] px-3 py-2.5 text-center last:border-r-0"><div className="text-[8px] uppercase tracking-[0.19em] text-[#9f8b63]">{label}</div><div className="mt-1 flex items-center justify-center gap-1.5 font-serif text-[22px] text-[#eadcbc]">{icon && <span className="text-[#d4ad62]">{icon}</span>}<span>{value}</span></div><div className="absolute inset-x-[18%] bottom-0 h-px" style={{ background: `linear-gradient(90deg,transparent,${accent}80,transparent)` }} /></div>
}
function AbilityCell({ label, score, mod, accent }: { label: string; score: number | null | undefined; mod: number; accent: string }) {
  return <div className="relative border-r border-[#49371f] py-2 text-center last:border-r-0"><div className="font-serif text-[10px] tracking-[0.12em] text-[#c4ad7b]">{label}</div><div className="font-serif text-[22px] leading-tight text-[#f1dfb9]">{sign(mod)}</div><div className="font-serif text-[10px] text-[#75684e]">{score ?? "—"}</div><span className="absolute bottom-0 left-1/2 h-[3px] w-[22px] -translate-x-1/2 rounded-full" style={{ backgroundColor: accent, boxShadow: `0 0 7px ${accent}` }} /></div>
}
function MiniMedallion({ label, score, mod, accent }: { label: string; score: number | string; mod?: number | null; accent: string }) {
  return <div className="relative w-[82px] text-center">{mod != null && <span className="absolute -left-1 top-0 z-20 grid h-[25px] w-[25px] place-items-center rounded-full border bg-[#080608] font-serif text-[10px] text-[#f2dfb6]" style={{ borderColor: accent, boxShadow: `0 0 9px ${accent}aa` }}>{sign(mod)}</span>}<div className="mx-auto grid h-[66px] w-[66px] place-items-center rounded-full border-2 bg-[radial-gradient(circle_at_42%_30%,#25222b,#070608_68%)] font-serif text-[23px] text-[#f0e1bd]" style={{ borderColor: "#846637", boxShadow: `inset 0 0 20px #000,0 0 13px ${accent}45` }}>{score}</div><div className="-mt-1 border border-[#58431f] bg-[#080607]/95 px-1 py-1 font-serif text-[7px] uppercase tracking-[0.08em] text-[#bea978]">{label}</div></div>
}
function SpellRow({ name, accent }: { name: string; accent: string }) {
  const art = iconFor(name)
  return <div className="group flex min-h-[58px] items-center gap-3 border-b border-[#332719] px-1.5 py-1.5 last:border-0"><div className="relative h-[48px] w-[48px] shrink-0 overflow-hidden border border-[#775a2c] bg-[#050405]" style={{ boxShadow: `0 0 10px ${accent}22,inset 0 0 0 1px #d6ab5720` }}>{art ? <img src={art} alt={name} className="h-full w-full object-cover brightness-[1.02] saturate-[1.12] transition group-hover:brightness-125" /> : <div className="grid h-full w-full place-items-center px-1 text-center font-serif text-[7px] text-[#cfbd96]">{name}</div>}</div><span className="min-w-0 truncate font-serif text-[12px] tracking-[0.03em] text-[#ded0ae]">{name}</span></div>
}
function HotbarTile({ name, hotkey, accent }: { name: string; hotkey: number; accent: string }) {
  const art = iconFor(name)
  return <div className="group relative w-[104px] shrink-0 text-center"><div className="relative mx-auto h-[72px] w-[72px] overflow-hidden border border-[#75582a] bg-[#050405]" style={{ boxShadow: `0 0 12px ${accent}25,inset 0 0 0 1px #e2b85c24` }}>{art ? <img src={art} alt={name} className="h-full w-full object-cover saturate-[1.15] transition group-hover:brightness-125" /> : <div className="grid h-full w-full place-items-center px-2 font-serif text-[8px] text-[#d6c29a]">{name}</div>}<span className="absolute left-0 top-0 grid h-[18px] min-w-[18px] place-items-center border-r border-b border-[#81602c] bg-black/90 px-1 font-serif text-[8px] text-[#f1cf76]">{hotkey}</span></div><div className="mt-1 min-h-[28px] font-serif text-[9px] uppercase leading-[1.1] tracking-[0.03em] text-[#cdbb92]">{name}</div></div>
}
function CombatLogPanel({ log, accent }: { log: HudLogLine[]; accent: string }) {
  return <GothicPanel title="Combat Log" className="h-full" accent={accent}><div className="max-h-[365px] overflow-y-auto pr-1">{log.length === 0 ? <div className="py-8 text-center font-serif text-[10px] italic text-[#6d6250]">The dark is quiet.</div> : log.slice(-10).map((line) => { const hostile = /takes|damage|critical|wounded|misses/i.test(line.text); return <div key={line.id} className="border-b border-[#2b2118] py-2.5 text-[11px] leading-[1.45] last:border-0"><span className={line.speaker === "Malachar" ? "font-serif text-[#bd7ee9]" : "font-serif text-[#decda9]"}>{line.speaker}</span><span className={hostile ? " text-[#d15b4b]" : " text-[#aaa087]"}> {line.text}</span></div> })}</div></GothicPanel>
}
function VioletStage({ hero, name, accent }: { hero: string | null | undefined; name: string; accent: string }) {
  return <div className="absolute inset-0 overflow-hidden bg-[#08040d]">
    <div className="absolute inset-0 opacity-95" style={{ backgroundImage: ["radial-gradient(circle at 72% 40%,rgba(177,69,241,.46),transparent 17%)","radial-gradient(circle at 47% 30%,rgba(91,35,139,.46),transparent 36%)","radial-gradient(circle at 18% 55%,rgba(59,18,89,.58),transparent 28%)","linear-gradient(180deg,#0b0611 0%,#100817 38%,#060307 100%)"].join(",") }} />
    <div className="absolute inset-0 opacity-35" style={{ backgroundImage: "repeating-linear-gradient(90deg,transparent 0 42px,rgba(65,48,77,.34) 43px 47px,transparent 48px 92px)" }} />
    <div className="absolute inset-x-[7%] top-[8%] h-[58%] rounded-[50%] border border-[#56356c]/40 shadow-[inset_0_0_70px_#3c185d66]" />
    {[12,20,30,73,82,89].map((left,i)=><span key={left} className="absolute h-[4px] w-[3px] rounded-full bg-[#ffbd67] shadow-[0_0_8px_#ff8a32]" style={{ left:`${left}%`, top:`${22+(i%3)*15}%` }} />)}
    {hero ? <><img src={hero} alt="" aria-hidden className="absolute inset-[3%] h-[94%] w-[94%] object-cover object-[50%_22%] opacity-50" style={{ filter:"contrast(1.2) brightness(.62) saturate(.5)", mixBlendMode:"luminosity", maskImage:"radial-gradient(ellipse at 50% 42%,black 35%,rgba(0,0,0,.9) 55%,transparent 82%)" }} /><img src={hero} alt={name} className="absolute bottom-0 left-1/2 h-[96%] w-[82%] -translate-x-1/2 object-cover object-[50%_18%]" style={{ filter:"contrast(1.08) brightness(.9) saturate(.84)", maskImage:"radial-gradient(ellipse at 50% 40%,black 28%,rgba(0,0,0,.98) 46%,rgba(0,0,0,.42) 67%,transparent 84%)", WebkitMaskImage:"radial-gradient(ellipse at 50% 40%,black 28%,rgba(0,0,0,.98) 46%,rgba(0,0,0,.42) 67%,transparent 84%)" }} /></> : <div className="grid h-full w-full place-items-center font-serif text-7xl" style={{ color:accent }}>{name.slice(0,1)}</div>}
    <div className="absolute inset-0 bg-[linear-gradient(90deg,#060308aa_0%,transparent_18%,transparent_78%,#060308bb_100%)]" /><div className="absolute inset-x-0 bottom-0 h-[26%] bg-gradient-to-t from-[#050305] via-[#050305b8] to-transparent" /><div className="pointer-events-none absolute right-[9%] top-[35%] h-[180px] w-[180px] rounded-full border border-[#b55cf5]/30 shadow-[0_0_45px_#8e3bce88,inset_0_0_40px_#7b2cb866]" /><div className="pointer-events-none absolute right-[16%] top-[43%] h-[75px] w-[75px] rounded-full bg-[#b457ef25] blur-xl" />
  </div>
}

export function CharacterSheetOverlay({ character: c, onClose, onEndTurn, log = [] }: { character: HudCharacter; onClose: () => void; onEndTurn?: () => void; log?: HudLogLine[] }) {
  useEffect(() => { const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose()}; window.addEventListener("keydown",onKey); return()=>window.removeEventListener("keydown",onKey) }, [onClose])
  const cls=frameForClass(c.class)
  const isKenta=c.name.trim().toLowerCase()==="kenta"
  const accent=isKenta?"#a94ee9":cls.accent
  const scores:Record<AbilKey,number|null|undefined>={str:c.str_score,dex:c.dex_score,con:c.con_score,int:c.int_score,wis:c.wis_score,cha:c.cha_score}
  const modOf=(k:AbilKey)=>{const v=scores[k];return v==null?0:Math.floor((v-10)/2)}
  const prof=c.proficiency_bonus??2
  const saveProf=new Set((Array.isArray(c.sheet_save_proficiencies)?c.sheet_save_proficiencies:[]).map((x)=>String(x).toLowerCase()))
  const skillProfRaw=(c.sheet_skill_proficiencies??{}) as Record<string,unknown>
  const skillProf=new Set(Object.keys(skillProfRaw).map((k)=>k.toLowerCase()))
  const saveMod=(k:AbilKey)=>modOf(k)+(saveProf.has(k)?prof:0)
  const skillMod=(name:string,k:AbilKey)=>modOf(k)+(skillProf.has(name.toLowerCase())?prof:0)
  const sc=c.sheet_spellcasting??{}
  const cantrips=sc.cantrips??[]
  const prepared=sc.prepared??[]
  const slotRows=Object.entries(sc.slots??{}).sort(([a],[b])=>Number(a)-Number(b))
  const slotsMax=slotRows.reduce((n,[,v])=>n+(v?.max??0),0)
  const slotsUsed=slotRows.reduce((n,[,v])=>n+(v?.used??0),0)
  const slotsRemaining=Math.max(0,slotsMax-slotsUsed)
  const attacks=Array.isArray(c.sheet_attacks)?c.sheet_attacks:[]
  const rack=[...cantrips,...prepared].slice(0,6)
  const xp=c.xp??0, xpNext=c.xp_to_next??0, xpPct=xpNext>0?Math.min(100,Math.round((xp/xpNext)*100)):0
  const hero=c.hero_image_url||c.avatar_image_url||c.portrait_image_url
  const hpCur=c.hp_current??c.hp_max??0, hpMax=c.hp_max??0, initiative=c.initiative??c.dex_modifier??0
  return <div className="pointer-events-auto fixed inset-0 z-[70] flex items-center justify-center bg-black/95 p-2 backdrop-blur-[3px]" onClick={onClose}>
    <div onClick={(e)=>e.stopPropagation()} className="relative flex h-[min(97vh,960px)] w-full max-w-[1480px] flex-col overflow-hidden border-2 border-[#6c5229] bg-[#050405] shadow-[0_0_100px_#000]" style={{ backgroundImage:isKenta?"radial-gradient(ellipse at 52% 40%,rgba(110,43,157,.24),transparent 39%),linear-gradient(180deg,#0c080e,#050405 56%,#020202)":"linear-gradient(180deg,#0b0806,#050403)" }}>
      <div className="pointer-events-none absolute inset-[4px] z-50 border border-[#d0a4512b]" /><div className="pointer-events-none absolute inset-[9px] z-50 border border-[#302319]" /><i className="pointer-events-none absolute left-2 top-2 z-[60] h-4 w-4 rotate-45 border border-[#9a7638] bg-[#080608]" /><i className="pointer-events-none absolute right-2 top-2 z-[60] h-4 w-4 rotate-45 border border-[#9a7638] bg-[#080608]" />
      <header className="relative z-10 grid h-[136px] shrink-0 grid-cols-[132px_590px_1fr] border-b border-[#5b4423] bg-[#050405]/80">
        <div className="relative overflow-hidden border-r border-[#5b4423] p-1.5"><ClassMedallion faceUrl={c.face_image_url} portraitUrl={c.portrait_image_url} characterClass={c.class} className="scale-[1.08]" fallback={<span className="font-serif text-4xl" style={{color:accent}}>{c.name.slice(0,1)}</span>} /></div>
        <div className="min-w-0 px-5 py-3"><h2 className="truncate font-serif text-[34px] font-semibold uppercase tracking-[0.08em] text-[#f1e4c8] [text-shadow:0_2px_10px_#000]">{c.name}</h2><div className="font-serif text-[14px] uppercase tracking-[0.21em]" style={{color:accent,textShadow:`0 0 12px ${accent}66`}}>Level {c.level??"—"} {c.class??"Adventurer"}{c.subclass?` · ${c.subclass}`:""}</div><div className="mt-3 flex border-y border-[#4a371f]"><CoreStat label="HP" value={`${hpCur}/${hpMax||"—"}`} icon="♥" accent={accent}/><CoreStat label="AC" value={c.ac??"—"} icon="◈" accent={accent}/><CoreStat label="Initiative" value={sign(initiative)} accent={accent}/><CoreStat label="Speed" value={c.speed||"—"} accent={accent}/></div></div>
        <div className="flex min-w-0 items-start justify-end gap-2 px-4 py-3">{[["Race",c.sheet_species??"—"],["Background",c.sheet_background??"—"]].map(([label,value])=><div key={label} className="w-[130px] border border-[#594221] bg-[#090708]/90 px-3 py-2 text-center"><div className="text-[7px] uppercase tracking-[0.19em] text-[#8f7a51]">{label}</div><div className="mt-1 truncate font-serif text-[16px] text-[#e4d5b2]">{value}</div></div>)}<div className="w-[190px] border border-[#594221] bg-[#090708]/90 px-3 py-2"><div className="text-center text-[7px] uppercase tracking-[0.19em] text-[#8f7a51]">Experience Points</div><div className="mt-1 text-center font-serif text-[14px] text-[#e4d5b2]">{xp} / {xpNext||"—"}</div><div className="mt-2 h-[5px] overflow-hidden bg-[#160d1b]"><div className="h-full" style={{width:`${xpPct}%`,background:`linear-gradient(90deg,#5d2782,${accent})`,boxShadow:`0 0 8px ${accent}`}}/></div></div><button onClick={onClose} className="border border-[#705328] bg-[#0b0807] px-4 py-2 font-serif text-[9px] uppercase tracking-[0.22em] text-[#d6b56e] hover:border-[#ad8240]">Close</button></div>
      </header>
      <main className="relative z-10 grid min-h-0 flex-1 grid-cols-[330px_88px_minmax(500px,1fr)_430px] overflow-hidden">
        <div className="min-h-0 border-r border-[#4b381f] bg-[#070607]/82 p-2.5"><div className="grid grid-cols-6 border border-[#554020] bg-[#080607]">{(Object.keys(ABIL) as AbilKey[]).map((k)=><AbilityCell key={k} label={ABIL[k]} score={scores[k]} mod={modOf(k)} accent={accent}/>)}</div><div className="mt-2.5"><GothicPanel title="Saving Throws" accent={accent}><div className="grid grid-cols-6 gap-1">{(Object.keys(ABIL) as AbilKey[]).map((k)=><div key={k} className="text-center"><div className="font-serif text-[8px] text-[#94825e]">{ABIL[k]}</div><div className={saveProf.has(k)?"font-serif text-[14px] text-[#f0d27f]":"font-serif text-[14px] text-[#bfb094]"}>{sign(saveMod(k))}</div></div>)}</div><div className="mt-1.5 text-center text-[7px] text-[#6f644f]">Saving throw modifiers · proficiency {sign(prof)}</div></GothicPanel></div><div className="mt-2.5 h-[calc(100%-154px)]"><GothicPanel title="Skills" className="h-full" accent={accent}><div className="max-h-[405px] overflow-y-auto pr-1">{SKILLS.map(([name,k])=>{const isProf=skillProf.has(name.toLowerCase());return <div key={name} className="flex items-center gap-2 border-b border-[#2c2118] px-1 py-[4px] last:border-0"><span className="h-[8px] w-[8px] rotate-45 border" style={{borderColor:isProf?accent:"#4e412e",backgroundColor:isProf?accent:"transparent",boxShadow:isProf?`0 0 6px ${accent}`:undefined}}/><span className={isProf?"min-w-0 flex-1 truncate text-[9px] text-[#e4d7bc]":"min-w-0 flex-1 truncate text-[9px] text-[#978c76]"}>{name} <small className="text-[7px] text-[#6f6553]">({ABIL[k]})</small></span><span className="font-serif text-[10px] text-[#d3bd8b]">{sign(skillMod(name,k))}</span></div>})}</div></GothicPanel></div></div>
        <div className="relative z-20 flex flex-col items-center gap-5 border-r border-[#41301c] bg-[#070507]/85 pt-5"><MiniMedallion label="Proficiency Bonus" score={sign(prof)} accent={accent}/><MiniMedallion label="Intelligence" score={scores.int??"—"} mod={modOf("int")} accent={accent}/><MiniMedallion label="Wisdom" score={scores.wis??"—"} mod={modOf("wis")} accent={accent}/><MiniMedallion label="Charisma" score={scores.cha??"—"} mod={modOf("cha")} accent={accent}/></div>
        <div className="relative min-h-0 border-r border-[#4b381f]">{isKenta?<VioletStage hero={hero} name={c.name} accent={accent}/>:<div className="absolute inset-0 bg-[#080605]">{hero&&<img src={hero} alt={c.name} className="h-full w-full object-contain object-bottom"/>}</div>}<div className="absolute inset-x-5 bottom-5 space-y-2">{attacks.slice(0,2).map((a,i)=>{const atk=a as {name?:string;type?:string;hit?:string;damage?:string;range?:string};return <div key={i} className="grid grid-cols-[1fr_70px_120px] border border-[#6d5127] bg-[#080607]/94 shadow-[0_5px_18px_#000c]"><div className="px-4 py-2"><div className="font-serif text-[15px] uppercase text-[#e6d5af]">{atk.name??"Attack"}</div><div className="text-[8px] text-[#8e8067]">{atk.type??""}{atk.range?` · ${atk.range}`:""}</div></div><div className="border-l border-[#49361e] px-2 py-2 text-center"><div className="text-[7px] uppercase text-[#7e7058]">Hit</div><div className="font-serif text-[15px] text-[#e5bd65]">{atk.hit??""}</div></div><div className="border-l border-[#49361e] px-2 py-2"><div className="text-[7px] uppercase text-[#7e7058]">Damage</div><div className="font-serif text-[13px] text-[#ded0ae]">{atk.damage??""}</div></div></div>})}</div></div>
        <div className="grid min-h-0 grid-cols-[55%_45%] gap-2 bg-[#070607]/82 p-2.5"><div className="min-h-0 space-y-2.5 overflow-y-auto"><GothicPanel title="Spellcasting" accent={accent}><div className="mb-2 flex items-center justify-between text-[8px] uppercase tracking-[0.14em] text-[#8f7b58]"><span>Save DC <b className="ml-1 font-serif text-[12px] text-[#dac59d]">{sc.save_dc??"—"}</b></span><span>Attack <b className="ml-1 font-serif text-[12px] text-[#dac59d]">{sc.attack_bonus==null?"—":sign(sc.attack_bonus)}</b></span></div>{slotRows.map(([lvl,s])=>{const max=s?.max??0,used=s?.used??0,rem=Math.max(0,max-used);return <div key={lvl} className="mb-2 flex items-center justify-between border-y border-[#30251a] py-1.5"><span className="font-serif text-[9px] uppercase text-[#9f875c]">Level {lvl}</span><span className="flex gap-1.5">{Array.from({length:max}).map((_,i)=><i key={i} className="h-[13px] w-[13px] rotate-45 border" style={{borderColor:accent,backgroundColor:i<rem?accent:"#110d14",boxShadow:i<rem?`0 0 9px ${accent}`:undefined}}/>)}</span></div>})}{cantrips.length>0&&<><div className="mt-2 text-[8px] uppercase tracking-[0.2em] text-[#846f4a]">Cantrips</div>{cantrips.map((n)=><SpellRow key={n} name={n} accent={accent}/>)}</>}{prepared.length>0&&<><div className="mt-3 text-[8px] uppercase tracking-[0.2em] text-[#846f4a]">Known / Prepared Spells</div>{prepared.map((n)=><SpellRow key={n} name={n} accent={accent}/>)}</>}</GothicPanel><GothicPanel title="Equipment" accent={accent}><div className="flex items-center gap-3 py-1"><div className="grid h-11 w-11 place-items-center border border-[#614924] bg-[#080607] text-xl">⚔</div><div className="font-serif text-[10px] leading-relaxed text-[#bbaa88]">{attacks.length?attacks.slice(0,2).map((a)=>(a as {name?:string}).name).filter(Boolean).join(" · "):"Equipment follows the live character sheet."}</div></div></GothicPanel></div><div className="min-h-0 space-y-2.5"><div className="h-[calc(100%-170px)] min-h-[310px]"><CombatLogPanel log={log} accent={accent}/></div>{onEndTurn&&<button onClick={onEndTurn} className="w-full border-2 border-[#775023] bg-[linear-gradient(180deg,#37170f,#160906_60%,#080403)] py-4 font-serif text-[16px] uppercase tracking-[0.17em] text-[#efc875] shadow-[0_5px_0_#030201,0_8px_20px_#000b,inset_0_1px_0_#f2c46f30] hover:border-[#be8233] hover:text-[#fff0bd]">End Turn</button>}<GothicPanel title="Bonus Action" accent={accent}><div className="flex justify-center gap-3 py-2">{Array.from({length:5}).map((_,i)=><i key={i} className="h-[12px] w-[12px] rotate-45 border" style={{borderColor:i<2?accent:"#4c3e2d",backgroundColor:i<2?accent:"#080607",boxShadow:i<2?`0 0 8px ${accent}`:undefined}}/>)}</div></GothicPanel></div></div>
      </main>
      <footer className="relative z-20 grid h-[176px] shrink-0 grid-cols-[190px_1fr_190px] items-end border-t border-[#604720] bg-[linear-gradient(180deg,#0b0808,#030203)] px-5 pb-2 pt-3 shadow-[0_-12px_30px_#000c]"><div className="flex justify-center"><Globe value={hpCur} max={hpMax} label="Hit Points" variant="life" size={148}/></div><div className="self-center overflow-hidden"><div className="mb-2 text-center font-serif text-[8px] uppercase tracking-[0.28em] text-[#8d7953]">Combat Abilities</div><div className="flex justify-center gap-1.5 border-y border-[#624922] bg-[#090708]/90 px-3 py-2">{rack.length?rack.map((name,i)=><HotbarTile key={`${name}-${i}`} name={name} hotkey={i+1} accent={accent}/>):<div className="px-8 py-8 font-serif text-[10px] italic text-[#6c604c]">No prepared abilities</div>}</div></div><div className="flex justify-center"><Globe value={slotsRemaining} max={slotsMax} label="Spell Slots" variant="mana" size={148}/></div></footer>
    </div>
  </div>
}
