-- SCENE KEY REGISTRY (2026-08-18) — applied to production 2026-08-18 00:30 UTC.
-- Naming protocol: humans and Malachar use display names; machines join on
-- scene_key, a slug generated by ONE function and never typed by hand.
-- environments is the central inventory: the unique index makes a second row
-- for the same place physically impossible, however it is spelled.
--
-- Context: free-text location naming created blank duplicate environment rows
-- ("Velkynvelve (slave pen)" alongside "Scene_1_Velkynvelve (slave pen)")
-- which broke cinematic resolution. PR #144 fixed the app path; this locks
-- the guarantee into the database itself.

-- 1. The subroutine. Canonical key from any human spelling.
--    "Scene_1_Velkynvelve (slave pen)" -> "velkynvelve-slave-pen"
create or replace function public.scene_key(p_name text)
returns text
language sql
immutable
set search_path to 'public'
as $$
  select nullif(
    regexp_replace(
      regexp_replace(
        regexp_replace(lower(coalesce(p_name, '')), '^scene[_\s-]*[0-9]+[_\s-]*', ''),
        '[^a-z0-9]+', '-', 'g'
      ),
      '(^-+|-+$)', '', 'g'
    ),
  '');
$$;

-- 2. Key columns.
alter table public.environments    add column if not exists scene_key text;
alter table public.cinematic_clips add column if not exists scene_key text;

-- 3. Auto-key triggers: the key is always derived, never written directly.
create or replace function public.environments_set_scene_key()
returns trigger language plpgsql set search_path to 'public' as $$
begin
  new.scene_key := public.scene_key(new.name);
  return new;
end $$;

create or replace function public.cinematic_clips_set_scene_key()
returns trigger language plpgsql set search_path to 'public' as $$
begin
  new.scene_key := public.scene_key(new.location);
  return new;
end $$;

drop trigger if exists trg_environments_scene_key on public.environments;
create trigger trg_environments_scene_key
  before insert or update of name on public.environments
  for each row execute function public.environments_set_scene_key();

drop trigger if exists trg_cinematic_clips_scene_key on public.cinematic_clips;
create trigger trg_cinematic_clips_scene_key
  before insert or update of location on public.cinematic_clips
  for each row execute function public.cinematic_clips_set_scene_key();

-- 4. Backfill existing rows.
update public.environments    set scene_key = public.scene_key(name);
update public.cinematic_clips set scene_key = public.scene_key(location);

-- 5. DEDUP before locking: quarantine (never silently discard) every ARTLESS
--    row whose key collides with an ARTED row, then remove it. Curated rows
--    are never touched.
create table if not exists public.environments_quarantine_scenekey as
  select e.* from public.environments e
  where e.background_image_url is null
    and exists (
      select 1 from public.environments k
      where k.scene_key = e.scene_key
        and k.id <> e.id
        and k.background_image_url is not null
    );

delete from public.environments e
  where e.background_image_url is null
    and exists (
      select 1 from public.environments k
      where k.scene_key = e.scene_key
        and k.id <> e.id
        and k.background_image_url is not null
    );

-- 6. The registry guarantee: one row per place, no matter the spelling.
create unique index if not exists environments_scene_key_uidx
  on public.environments (scene_key);
create index if not exists cinematic_clips_scene_key_idx
  on public.cinematic_clips (scene_key);

-- 7. resolve_cinematic v2: tiers unchanged, but location matching now runs
--    key-to-key, so a spelling variant can never again cause a miss.
create or replace function public.resolve_cinematic(
  p_location text,
  p_state text default null,
  p_scope text default 'party',
  p_kind text default 'environment'
)
returns table(clip_id uuid, video_url text, resolution text)
language sql
stable
security definer
set search_path to 'public'
as $$
  with req as (select public.scene_key(p_location) as k),
  tiers as (
    select c.id, c.video_url, c.weight,
           case
             when c.scene_key = req.k
              and p_state is not null
              and c.state is not distinct from p_state then 'exact'
             when c.scene_key = req.k and c.state is null then 'location_fallback'
             when c.location = 'generic'                  then 'generic_fallback'
           end as res,
           case
             when c.scene_key = req.k
              and p_state is not null
              and c.state is not distinct from p_state then 1
             when c.scene_key = req.k and c.state is null then 2
             when c.location = 'generic'                  then 3
           end as tier
    from public.cinematic_clips c, req
    where c.scope = p_scope
      and c.kind  = p_kind
      and c.video_url is not null
      and c.weight > 0
      and (c.scene_key = req.k or c.location = 'generic')
  ),
  best as (select min(tier) as t from tiers where tier is not null)
  select t.id, t.video_url, t.res
  from tiers t, best
  where t.tier = best.t
  order by random() / greatest(t.weight, 1)
  limit 1;
$$;
